version: '3.8'

services:
  dons-backend:
    build: .
    container_name: dons-backend
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=dons-database-nl3z8n
      - DB_PORT=5432
      - DB_DATABASE=Dons
      - DB_USERNAME=postgres
      - DB_PASSWORD=9zctibtytwmv640w
      - APP_URL=http://213.199.48.58:8000
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - dons-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dons-network:
    driver: bridge
